### ISSUE TITLE
Twig as a service

### ISSUE THREAD

**Issue by mpoiriert** [manekinekko/angular-twig#1]
Hi,

do you have anything to use twig as a service ? I want to parse string that is coming from a file that is downloaded any way to do that ?

I could probably easily use the library you are based on directly but just wondering since you already integrated it in angular2

Thanks

**Comment by manekinekko** [comment]
Hi, you probably would need to use the Twig library I'm using here. I'm not planning on continuing working on this project for the time being.

Btw, I'm also open to any PR if you wanna contribute to this project.

**Comment by mpoiriert** [comment]
Thanks for the answer but finally I will need to stick on the backend side for the need I have. It was to manipulate SVG with variable and custom filter in it but looking different browser the svg will not be renderer exactly the same way (that part is really critical for my project) so I will need to convert the SVG in a png on the backend side.
